# Generated by Django 6.0.5 on 2026-05-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='score_comfort',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='score_noise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='score_plug',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='score_table',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='score_wifi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='total_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CafeReviewRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('naver_place', '네이버 플레이스'), ('naver_blog', '네이버 블로그')], max_length=20)),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_reviews', to='spaces.workspace')),
            ],
        ),
    ]
