# Generated by Django 5.2.15 on 2026-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_workspace_last_scored_at_workspace_score_comfort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='kakao_place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='kakao_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
